#spring:
#    shardingsphere:
#        datasource:
#            ds2:
#                driver-class-name: com.mysql.jdbc.Driver
#                jdbc-url: jdbc:mysql://localhost:3306/shardinghere?useUnicode=true&charactorEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#                password: 123456
#                type: com.zaxxer.hikari.HikariDataSource
#                username: root
#            slave0:
#                driver-class-name: com.mysql.jdbc.Driver
#                jdbc-url: jdbc:mysql://101.200.213.75:3306/shardinghere?useUnicode=true&charactorEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#                password: 123456
#                type: com.zaxxer.hikari.HikariDataSource
#                username: root
#            names: ds2,slave0
#        props:
#            sql:
#                show: true
#        sharding:
#            master-slave-rules:
#                ms0:
#                    master-data-source-name: slave0
#                    slave-data-source-names: ds2
#
#
